version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/data

  miniobuckets:
    image: minio/mc
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3; 
      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb myminio/${S3_BUCKET_NAME};
      exit 0;
      "

  api:
    build: .
    depends_on:
      - db
      - minio
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}


  redis:
    image: redis:6
    ports:
      - "6379:6379"
    command: bash -c "redis-server --requirepass ${REDIS_PASSWORD}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}


  celery:
    build: .
    depends_on:
      - api
      - redis
    command: celery -A app.tasks worker --loglevel=info
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

volumes:
  pgdata:
  minio-data:
